version: '3.3'
services:
  app:
    container_name: certm
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CERTM_DOMAIN_NAME: "example.com"
      CERTM_EMAIL: "rishat@example.com"
      CERTM_HAPROXY_CERTS_LOCATION: "/etc/haproxy/ssl"
      CERTM_LETSENCRYPT_CERTS_LOCATION: "/etc/letsencrypt/live"
      CERTM_CERTBOT_PORT: "9080"
      CERTM_S3_ENDPOINT: "your_endpoint"
      CERTM_S3_BUCKET_NAME: "certm"
      CERTM_S3_ACCESS_KEY: "your_key"
      CERTM_S3_PRIVATE_KEY: "your_private_key"
      TZ: Asia/Almaty

    command: certm start --puller